export type Category = "Commercial Painting" | "DIY" | "News" | "Residential painting";

export const CATEGORY_SLUGS: Record<Category, string> = {
  "Commercial Painting": "commercial-painting",
  DIY: "diy",
  News: "news",
  "Residential painting": "residential-painting",
};

export const CATEGORIES = Object.keys(CATEGORY_SLUGS) as Category[];

export function categoryHref(category: Category) {
  return `/category/${CATEGORY_SLUGS[category]}/`;
}

export type BlogPost = {
  title: string;
  date: string;
  readTime: string;
  img: string;
  href: string;
  categories: Category[];
};

export const POSTS: BlogPost[] = [
  {
    title: "Sustainable Commercial Painting Practices: Eco-Friendly Tips",
    date: "August 20, 2026",
    readTime: "12 minutes read",
    img: "/images/sustainable-commercial-painting-chatgpt-image.jpg",
    href: "/sustainable-commercial-painting-eco-friendly-tips/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Prepare Surfaces Before Painting Commercial Buildings",
    date: "August 10, 2026",
    readTime: "14 minutes read",
    img: "/images/prepare-commercial-buildings-surfaces-for-painting-chatGPT-image-1.jpg",
    href: "/prepare-commercial-buildings-surfaces-for-painting/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How Painters Extend Sydney Home Exterior Lifespan",
    date: "July 20, 2026",
    readTime: "13 minutes read",
    img: "/images/twostory-building-with-a-yellow-and-pink-facade.jpg",
    href: "/how-painters-extend-sydney-home-exterior-lifespan/",
    categories: ["Residential painting"],
  },
  {
    title: "House Paint Colour Trends 2026: For Australian Homes",
    date: "July 10, 2026",
    readTime: "11 minutes read",
    img: "/images/house-paint-colour-2026-blog-banner.jpg",
    href: "/house-paint-colours-trend-2026/",
    categories: ["Residential painting"],
  },
  {
    title: "The Cost of Painting A Commercial Space",
    date: "June 20, 2026",
    readTime: "8 minutes read",
    img: "/images/view-of-sydney-in-cloudy-weather.jpg",
    href: "/cost-of-painting-commercial-buildings/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Winter Exterior Painting In Sydney: Essential Tips",
    date: "June 10, 2026",
    readTime: "3 minutes read",
    img: "/images/residential-house-with-front-yard-in-snow.jpg",
    href: "/winter-exterior-house-painting-dos-and-donts/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting Commercial Building: The Best Practice Guide",
    date: "May 20, 2026",
    readTime: "8 minutes read",
    img: "/images/colorful-building-facade-in-city.jpg",
    href: "/painting-commercial-building-the-best-practice-guide/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Essential Things to Know Before Painting Your Home Interiors",
    date: "May 10, 2026",
    readTime: "10 minutes read",
    img: "/images/repair-in-the-apartment-paints-the-wall-with-paint.jpg",
    href: "/things-to-know-before-painting-home-interiors/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Fix a Bad Paint Job: Common Painting Mistakes",
    date: "April 30, 2026",
    readTime: "9 minutes read",
    img: "/images/how-to-fix-bad-paint-job-blog-banner.jpg",
    href: "/how-to-fix-a-bad-paint-job/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Signs of a Bad Paint Job: Understand Painting Mistakes",
    date: "April 20, 2026",
    readTime: "9 minutes read",
    img: "/images/peeling-pink-and-yellow-paint-on-the-wall.jpg",
    href: "/signs-of-a-bad-paint-job/",
    categories: ["Residential painting"],
  },
  {
    title: "Paint, Colours, And Tools – Glossary You Need",
    date: "April 10, 2026",
    readTime: "7 minutes read",
    img: "/images/painting-glossary-blog-banner.jpg",
    href: "/paint-colours-and-tools-glossary-you-need/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Top Painting FAQs Answered by Professional Painters",
    date: "March 30, 2026",
    readTime: "9 minutes read",
    img: "/images/common-faqs-blog-banner.jpg",
    href: "/top-painting-faqs-answered-by-professional-painters/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Mistakes to Avoid When Hiring Residential Painters in Sydney",
    date: "March 20, 2026",
    readTime: "8 minutes read",
    img: "/images/man-painting-a-wall-with-a-paint-roller.jpg",
    href: "/mistakes-to-avoid-when-hiring-residential-painters/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Choose the Right Painter's Tape",
    date: "March 10, 2026",
    readTime: "6 minutes read",
    img: "/images/man-is-sticking-adhesive-tape-into-the-wall-1.jpg",
    href: "/how-to-choose-the-right-painters-tape/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Determine if Your House Has Lead Paint",
    date: "February 18, 2026",
    readTime: "7 minutes read",
    img: "/images/a-quiet-street-in-the-australian-country-town-of-pemberton.jpg",
    href: "/how-to-determine-if-your-house-has-lead-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Commercial Painting FAQs By Trusted Sydney Painters",
    date: "February 9, 2026",
    readTime: "8 minutes read",
    img: "/images/commercial-painting-faq-blog-banner.jpg",
    href: "/commercial-painting-faqs-by-trusted-sydney-painters/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Dulux Colour Forecast for 2026",
    date: "January 30, 2026",
    readTime: "5 minutes read",
    img: "/images/dulux-colour-forecast-for-2026-blog-banner.jpg",
    href: "/dulux-colour-forecast-for-2026/",
    categories: ["News"],
  },
  {
    title: "Limewash, Paint, or Render Your Brick House",
    date: "January 20, 2026",
    readTime: "9 minutes read",
    img: "/images/limewash-paint-or-render-your-brick-house-blog-banner.jpg",
    href: "/limewash-vs-paint-vs-render-for-brick-homes/",
    categories: ["Residential painting"],
  },
  {
    title: "Complete Guide to Interior and Exterior Painting",
    date: "January 10, 2026",
    readTime: "14 minutes read",
    img: "/images/residential-houses-at-battery-point-in-hobart-australia.jpg",
    href: "/complete-guide-to-interior-and-exterior-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Interior Painting Preparation",
    date: "December 10, 2025",
    readTime: "6 minutes read",
    img: "/images/woman-stands-in-the-middle-of-a-room-with-plastic-covered-furniture-and-a-stepladder.jpg",
    href: "/interior-painting-preparation/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Guide to Eggshell Paint Finish",
    date: "November 10, 2025",
    readTime: "6 minutes read",
    img: "/images/top-view-of-tin-with-purple-paint-and-brushes-on-blue-surface.jpg",
    href: "/guide-to-eggshell-paint-finish/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting Tips for Coastal Homes",
    date: "October 30, 2025",
    readTime: "7 minutes read",
    img: "/images/residential-houses-bunbury-australia.jpg",
    href: "/painting-tips-for-coastal-homes/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting Metal Roof – Tips & Tricks",
    date: "October 20, 2025",
    readTime: "7 minutes read",
    img: "/images/painting-metal-roof-blog-banner.jpg",
    href: "/metal-roof-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Paint to Maximise Space in Small Apartments",
    date: "October 10, 2025",
    readTime: "7 minutes read",
    img: "/images/house-bloks-of-flats-in-suburbs.jpg",
    href: "/paint-to-maximise-space-in-small-apartments/",
    categories: ["Residential painting"],
  },
  {
    title: "How Professional Painting Can Add Value to Your Property",
    date: "September 20, 2025",
    readTime: "4 minutes read",
    img: "/images/room-painting-job-painting-roller-in-hand-of-worker.jpg",
    href: "/how-professional-painting-adds-value-to-property/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Saving on House Painting Costs",
    date: "September 10, 2025",
    readTime: "8 minutes read",
    img: "/images/saving-on-house-painting-costs-blog-banner.jpg",
    href: "/saving-on-house-painting-costs/",
    categories: ["Residential painting"],
  },
  {
    title: "Paint Removal Tips For Restoring The Surfaces",
    date: "August 28, 2025",
    readTime: "8 minutes read",
    img: "/images/spatula-on-a-pink-surface.jpg",
    href: "/paint-removal-tips-restoring-surfaces/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Paint Over the Stained Wood",
    date: "August 21, 2025",
    readTime: "4 minutes read",
    img: "/images/hand-painting-blue-color-on-wooden-table.jpg",
    href: "/paint-over-the-stained-wood/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Colour Match Your Paint",
    date: "August 14, 2025",
    readTime: "5 minutes read",
    img: "/images/woman-with-palette-of-color-swatches-choosing-one-for-walls.jpg",
    href: "/how-to-colour-match-your-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Guide to Reglazing Windows",
    date: "August 7, 2025",
    readTime: "7 minutes read",
    img: "/images/windows-of-house.jpg",
    href: "/guide-to-reglazing-windows/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How Different Types of Exterior Siding Are Painted",
    date: "July 30, 2025",
    readTime: "8 minutes read",
    img: "/images/house-vinyl-siding.jpg",
    href: "/painting-different-exterior-siding/",
    categories: ["Residential painting"],
  },
  {
    title: "How Do Painting & Waterproofing Work Together",
    date: "July 20, 2025",
    readTime: "6 minutes read",
    img: "/images/worker-applies-bitumen-mastic-on-foundation.jpg",
    href: "/how-painting-waterproofing-work-together/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Paint Burnishing or Marring – Causes & Solutions",
    date: "July 10, 2025",
    readTime: "7 minutes read",
    img: "/images/wood-painting.jpg",
    href: "/paint-burnishing-marring-causes-solutions/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Fix Stress Cracks in Drywall",
    date: "June 18, 2025",
    readTime: "7 minutes read",
    img: "/images/cracked-wall-next-to-door-frame.jpg",
    href: "/how-to-fix-stress-cracks-in-drywall/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How Can Paint Colour Affects Your Work Spaces",
    date: "June 11, 2025",
    readTime: "4 minutes read",
    img: "/images/hybrid-working-model-collage-scaled.jpg",
    href: "/how-paint-colour-affects-your-work-spaces/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Buildings Stucco Painting & Repairing",
    date: "June 4, 2025",
    readTime: "6 minutes read",
    img: "/images/residential-apartment-and-flat-building-exterior.jpg",
    href: "/buildings-stucco-painting-repairing/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Different Types of Industrial Coatings",
    date: "May 25, 2025",
    readTime: "8 minutes read",
    img: "/images/different-types-of-industrial-coatings-blog-banner.jpg",
    href: "/different-types-of-industrial-coatings/",
    categories: ["Commercial Painting"],
  },
  {
    title: "House Painting Secrets",
    date: "May 21, 2025",
    readTime: "5 minutes read",
    img: "/images/walls-are-painted-in-blue-and-orange-hues.jpg",
    href: "/house-painting-secrets/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Safe Painting Practices for Homeowners & Painters",
    date: "May 14, 2025",
    readTime: "4 minutes read",
    img: "/images/safe-painting-practices-blog-banner.jpg",
    href: "/safe-painting-practices-for-homeowners-painters/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting A Foyer – Transform the Entryway",
    date: "May 7, 2025",
    readTime: "4 minutes read",
    img: "/images/entrance-hallway-with-staircase.jpg",
    href: "/painting-foyer-transform-the-entryway/",
    categories: ["Residential painting"],
  },
  {
    title: "Efflorescence in Masonry",
    date: "April 28, 2025",
    readTime: "4 minutes read",
    img: "/images/white-texture-brick-wall.jpg",
    href: "/efflorescence-in-masonry/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Guide on Surfactant Leaching",
    date: "April 21, 2025",
    readTime: "3 minutes read",
    img: "/images/brush-dipped-in-a-jar-with-paint.jpg",
    href: "/how-to-fix-surfactant-leaching/",
    categories: ["Residential painting"],
  },
  {
    title: "Removing Paint from Glass",
    date: "April 14, 2025",
    readTime: "3 minutes read",
    img: "/images/how-to-remove-paint-from-glass-blog-banner.jpg",
    href: "/how-to-remove-paint-from-glass/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Protect Your House Exterior Painting",
    date: "April 7, 2025",
    readTime: "3 minutes read",
    img: "/images/how-to-protect-house-exterior-paint-blog-banner.jpg",
    href: "/how-to-protect-house-exterior-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Paint Scraping vs. Pressure Washing",
    date: "March 30, 2025",
    readTime: "4 minutes read",
    img: "/images/paint-scraping-vs-pressure-washing-blog-banner.jpg",
    href: "/paint-scraping-vs-pressure-washing/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "What Type of Paint to Use & Why",
    date: "March 20, 2025",
    readTime: "4 minutes read",
    img: "/images/paint-front-door-of-country-home.jpg",
    href: "/what-type-of-paint-to-use-why/",
    categories: ["Residential painting"],
  },
  {
    title: "Use Accent Colours on Your Home's Exterior",
    date: "March 10, 2025",
    readTime: "4 minutes read",
    img: "/images/colorful-houses-on-a-leafy-residential-street.jpg",
    href: "/use-accent-colours-on-your-homes-exterior/",
    categories: ["Residential painting"],
  },
  {
    title: "Paint a Ceiling Without Splatter",
    date: "February 24, 2025",
    readTime: "3 minutes read",
    img: "/images/painter-is-painting-house-ceiling.jpg",
    href: "/paint-a-ceiling-without-splatter/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Practical Tips for Bathroom Painting",
    date: "February 18, 2025",
    readTime: "3 minutes read",
    img: "/images/bathroom-with-cabinets-and-window.jpg",
    href: "/practical-tips-for-bathroom-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Common Exterior Painting Mistakes",
    date: "February 12, 2025",
    readTime: "4 minutes read",
    img: "/images/private-house-exterior-with-a-garden.jpg",
    href: "/common-exterior-painting-mistakes/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Feature Wall Colour Ideas",
    date: "February 6, 2025",
    readTime: "3 minutes read",
    img: "/images/armchair-with-checkered-pattern-feature-wall.jpg",
    href: "/feature-wall-colour-ideas/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Top 5 Ways To Waterproof Commercial Buildings",
    date: "January 30, 2025",
    readTime: "5 minutes read",
    img: "/images/waterproofing-commercial-buildings.jpg",
    href: "/waterproofing-commercial-buildings/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How Pantone Colour 2025 Can Redefine Interiors",
    date: "December 26, 2024",
    readTime: "6 minutes read",
    img: "/images/pantone-colour-2025-mocha-mousse.png",
    href: "/pantone-colour-mocha-mousse-can-redefine-interiors/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Fix Flaky Ceiling",
    date: "December 19, 2024",
    readTime: "4 minutes read",
    img: "/images/smoothing-a-peeling-ceiling-with-spatula.jpg",
    href: "/how-to-fix-flaky-ceiling/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Paint Dry and Paint Cure",
    date: "December 12, 2024",
    readTime: "4 minutes read",
    img: "/images/paint-dry-paint-cure-blog-banner.jpg",
    href: "/paint-dry-and-paint-cure/",
    categories: ["DIY"],
  },
  {
    title: "Factors That Affect the Lifespan of House Paint",
    date: "December 5, 2024",
    readTime: "4 minutes read",
    img: "/images/brown-and-white-concrete-house.jpg",
    href: "/factors-affect-the-lifespan-of-house-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Spruce Up Your Home in Spring",
    date: "November 21, 2024",
    readTime: "4 minutes read",
    img: "/images/spring-spruce-up-blog-banner.jpg",
    href: "/spruce-up-your-home-in-spring/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Benefits of Hiring Commercial Painters",
    date: "November 14, 2024",
    readTime: "3 minutes read",
    img: "/images/renovation-crew-painting-in-a-room.jpg",
    href: "/benefits-of-hiring-commercial-painters/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Tips for Painting Your Fence",
    date: "November 7, 2024",
    readTime: "3 minutes read",
    img: "/images/planks-fence-dyeing-with-brown-paint-and-brush.jpg",
    href: "/tips-for-painting-your-fence/",
    categories: ["Residential painting"],
  },
  {
    title: "Drywall Repair Tips",
    date: "September 9, 2024",
    readTime: "5 minutes read",
    img: "/images/construction-worker-plastering-on-gypsum-walls.jpg",
    href: "/drywall-repair-tips/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Remove Wallpaper: A Step By Step Guide",
    date: "August 20, 2024",
    readTime: "4 minutes read",
    img: "/images/girl-removing-wallpaper-blog-banner.jpg",
    href: "/how-to-remove-wallpaper/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Pressure Wash Before Painting Your House",
    date: "August 14, 2024",
    readTime: "3 minutes read",
    img: "/images/man-is-cleaning-terrace-with-pressure-cleaner.jpg",
    href: "/pressure-wash-before-painting-your-house/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Pick the Perfect Beige Paint",
    date: "August 8, 2024",
    readTime: "4 minutes read",
    img: "/images/pick-the-perfect-beige-paint-blog-banner-1.jpg",
    href: "/how-to-pick-the-perfect-beige-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "VOC Paint vs. Low-VOC Paint vs. No-VOC Paint",
    date: "July 14, 2024",
    readTime: "3 minutes read",
    img: "/images/painter-holding-paint-can.jpg",
    href: "/voc-paint-vs-low-voc-paint-vs-no-voc-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Remove Old Paint from Walls",
    date: "July 7, 2024",
    readTime: "8 minutes read",
    img: "/images/texture-background-old-paint.jpg",
    href: "/how-to-remove-old-paint-from-walls/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "On-Site Preparation for Painters in Sydney",
    date: "June 20, 2024",
    readTime: "3 minutes read",
    img: "/images/instruments-for-repair-house-painting.jpg",
    href: "/on-site-preparation-for-painters-in-sydney/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Benefits of Getting Concrete Epoxy Coating",
    date: "June 13, 2024",
    readTime: "3 minutes read",
    img: "/images/garage-with-concrete-ceiling-flooring-scaled.jpg",
    href: "/benefits-of-getting-concrete-epoxy-coating/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Paint Your Property Before EOFY",
    date: "June 6, 2024",
    readTime: "3 minutes read",
    img: "/images/house-with-yard-sign-open-house-scaled.jpg",
    href: "/paint-your-property-before-eofy/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Venetian Plaster vs. Roman Clay vs. Limewash",
    date: "May 27, 2024",
    readTime: "7 minutes read",
    img: "/images/venetian-plaster-vs-roman-clay-vs-limewash-blog-banner-1.jpg",
    href: "/venetian-plaster-vs-roman-clay-vs-limewash/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting Concrete Driveway In Sydney: A How To Guide",
    date: "May 20, 2024",
    readTime: "8 minutes read",
    img: "/images/luxury-house-exterior-with-brick-and-siding-trim-and-double-garage.jpg",
    href: "/painting-your-concrete-driveway/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Match Wall Colour with Furniture",
    date: "May 13, 2024",
    readTime: "3 minutes read",
    img: "/images/interior-design-with-photoframes-blue-couch-scaled.jpg",
    href: "/match-wall-colour-with-furniture/",
    categories: ["Residential painting"],
  },
  {
    title: "The Best Paint Colours for Dark Rooms",
    date: "May 6, 2024",
    readTime: "4 minutes read",
    img: "/images/dark-room-inside-house-scaled.jpg",
    href: "/best-paint-colours-for-dark-rooms/",
    categories: ["Residential painting"],
  },
  {
    title: "Innovations in Paint Technology 2024",
    date: "April 28, 2024",
    readTime: "4 minutes read",
    img: "/images/paint-technology-innovations-2024-blog-banner.jpg",
    href: "/innovations-in-paint-technology-2024/",
    categories: ["News"],
  },
  {
    title: "Weatherproofing Your Home with Exterior Paint",
    date: "April 21, 2024",
    readTime: "4 minutes read",
    img: "/images/brown-and-white-concrete-house-near-green-grass-field-during-daytime-scaled.jpg",
    href: "/weatherproofing-your-home-with-exterior-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Benefits of Using Eco-Friendly Paints",
    date: "April 14, 2024",
    readTime: "4 minutes read",
    img: "/images/eco-friendly-paints-blog-banner.jpg",
    href: "/benefits-of-using-eco-friendly-paints/",
    categories: ["Residential painting"],
  },
  {
    title: "Difference Between Paint and Coatings",
    date: "April 7, 2024",
    readTime: "3 minutes read",
    img: "/images/top-view-paint-can-scaled.jpg",
    href: "/difference-between-paint-and-coatings/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Natural Ways to Eliminate the Smell of Fresh Paint",
    date: "March 28, 2024",
    readTime: "3 minutes read",
    img: "/images/ways-to-remove-paint-smell-blog-banner-1.jpg",
    href: "/ways-to-get-rid-of-paint-smells/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Paint Cladding Surfaces",
    date: "March 21, 2024",
    readTime: "4 minutes read",
    img: "/images/facade-of-a-regular-size-simple-house.jpg",
    href: "/how-to-paint-cladding-surfaces/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Tips for Painting Rendered Wall",
    date: "March 14, 2024",
    readTime: "3 minutes read",
    img: "/images/couple-painting-rendered-walls-together-scaled.jpg",
    href: "/tips-for-painting-rendered-wall/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Preparing a Weatherboard House for Painting",
    date: "March 7, 2024",
    readTime: "4 minutes read",
    img: "/images/weatherboard-house-siding-installation-scaled.jpg",
    href: "/preparing-weatherboard-house-for-painting/",
    categories: ["Residential painting"],
  },
  {
    title: "Protect Your Room & Furniture When Interior Painting",
    date: "February 27, 2024",
    readTime: "3 minutes read",
    img: "/images/man-protecting-floor-with-sheet-scaled.jpg",
    href: "/protect-room-furniture-when-interior-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Stain a Deck",
    date: "February 20, 2024",
    readTime: "3 minutes read",
    img: "/images/how-to-stain-a-deck-blog-banner.jpg",
    href: "/how-to-stain-a-deck/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Benefits of Painting Your Roof",
    date: "February 13, 2024",
    readTime: "3 minutes read",
    img: "/images/roofers-working-together-with-helmets-scaled.jpg",
    href: "/benefits-of-painting-your-roof/",
    categories: ["Residential painting"],
  },
  {
    title: "Ways to Store Leftover Paint",
    date: "February 6, 2024",
    readTime: "3 minutes read",
    img: "/images/ways-to-store-leftover-paint-blog-banner.jpg",
    href: "/ways-to-store-leftover-paint/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Why Do You Need Stain-Resistant Paints?",
    date: "January 22, 2024",
    readTime: "9 minutes read",
    img: "/images/stain-resistant-paint-scaled.jpg",
    href: "/why-stain-resistant-paint/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Painting Over Mould & Damp Walls: Expert Advice",
    date: "January 21, 2024",
    readTime: "6 minutes read",
    img: "/images/painting-over-mould-blog-banner.jpg",
    href: "/painting-over-mould/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Best Paint Colours for Small Rooms",
    date: "January 18, 2024",
    readTime: "3 minutes read",
    img: "/images/gray-fabric-loveseat-near-brown-wooden-table.jpg",
    href: "/best-paint-colours-for-small-rooms/",
    categories: ["Residential painting"],
  },
  {
    title: "Top Interior Paint Ideas for 2024: Elevate Your Space with Colour",
    date: "January 11, 2024",
    readTime: "3 minutes read",
    img: "/images/orange-and-black-sofa-with-throw-pillows-scaled.jpg",
    href: "/top-interior-paint-ideas-for-2024/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Clean Painted Walls",
    date: "January 4, 2024",
    readTime: "3 minutes read",
    img: "/images/hand-in-a-rubber-yellow-glove-wipes-a-chalked-heart-on-a-wall-with-a-sponge.jpg",
    href: "/how-to-clean-painted-walls/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How Often Should You Paint Your House",
    date: "December 31, 2023",
    readTime: "8 minutes read",
    img: "/images/how-often-should-you-paint-your-house-blog-banner.jpg",
    href: "/how-often-should-you-paint-your-house/",
    categories: ["Residential painting"],
  },
  {
    title: "Extend the Lifespan of Commercial Paint Job",
    date: "December 28, 2023",
    readTime: "3 minutes read",
    img: "/images/room-with-pendant-lamps-and-rectangular-dining-set.jpg",
    href: "/extend-the-lifespan-of-commercial-paint-job/",
    categories: ["Commercial Painting"],
  },
  {
    title: "When to Use the Primer, Sealer & Undercoat",
    date: "December 21, 2023",
    readTime: "3 minutes read",
    img: "/images/young-couple-repairs-room.jpg",
    href: "/when-to-use-primer-vs-sealer-vs-undercoat/",
    categories: ["Residential painting"],
  },
  {
    title: "The Difference Between Interior & Exterior Paint",
    date: "December 17, 2023",
    readTime: "6 minutes read",
    img: "/images/house-painting.jpg",
    href: "/difference-between-interior-exterior-paint/",
    categories: ["Residential painting"],
  },
  {
    title: "Ideas to Make A Small Room Look Bigger",
    date: "December 14, 2023",
    readTime: "3 minutes read",
    img: "/images/brown-wooden-chair-near-brown-wooden-table.jpg",
    href: "/ideas-to-make-small-room-look-bigger/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Summer Paint Colours to Cool Your Home",
    date: "December 7, 2023",
    readTime: "3 minutes read",
    img: "/images/kitchen-with-island-and-table.jpg",
    href: "/summer-paint-colours-to-cool-your-home/",
    categories: ["Residential painting"],
  },
  {
    title: "Signs It's Time to Repaint Your House",
    date: "November 30, 2023",
    readTime: "6 minutes read",
    img: "/images/gray-wooden-house-scaled.jpg",
    href: "/signs-its-time-to-repaint-your-house/",
    categories: ["Residential painting"],
  },
  {
    title: "Paint Your House in the Right Order",
    date: "November 27, 2023",
    readTime: "4 minutes read",
    img: "/images/young-man-painting-blue-wall-scaled.jpg",
    href: "/paint-your-house-in-the-right-order/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Treat & Prevent Mould on Walls",
    date: "November 20, 2023",
    readTime: "4 minutes read",
    img: "/images/white-ceramic-bathtub-scaled.jpg",
    href: "/how-to-treat-prevent-mould-on-walls/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Paint Colours That Make Your Home Look Cleaner",
    date: "November 13, 2023",
    readTime: "4 minutes read",
    img: "/images/cozy-dining-room-interior-with-wooden-furniture-scaled.jpg",
    href: "/paint-colours-that-make-your-home-look-cleaner/",
    categories: ["Residential painting"],
  },
  {
    title: "DIY Painting vs Hiring a Professional Painter",
    date: "November 6, 2023",
    readTime: "3 minutes read",
    img: "/images/diy-painting-vs-hiring-professional-painter-blog-banner.jpg",
    href: "/diy-painting-vs-hiring-professional-painter/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Paint Concrete Retaining Wall",
    date: "October 30, 2023",
    readTime: "6 minutes read",
    img: "/images/concrete-retaining-wall-blog-banner.jpg",
    href: "/how-to-paint-concrete-retaining-wall/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "The Best Time to Paint Your House",
    date: "October 26, 2023",
    readTime: "4 minutes read",
    img: "/images/charming-yellow-house-with-wooden-windows-green-grassy-garden-scaled.jpg",
    href: "/best-time-to-paint-your-house/",
    categories: ["Residential painting"],
  },
  {
    title: "Difference Between Commercial & Residential Painting",
    date: "October 19, 2023",
    readTime: "4 minutes read",
    img: "/images/commercial-vs-residential-painting-blog-banner.png",
    href: "/difference-between-commercial-vs-residential-painting/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "Brick Makeover Guide: Limewash, Whitewash, German Smear",
    date: "October 16, 2023",
    readTime: "9 minutes read",
    img: "/images/mountview-redbank-plains.jpg",
    href: "/brick-makeover-limewash-whitewash-german-smear/",
    categories: ["Residential painting"],
  },
  {
    title: "Ways to Touch Up Without Painting the Whole Wall",
    date: "October 12, 2023",
    readTime: "4 minutes read",
    img: "/images/people-renovating-house-scaled.jpg",
    href: "/touch-up-without-painting-the-whole-wall/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "How to Repair Peeling Paint on Wall",
    date: "October 5, 2023",
    readTime: "4 minutes read",
    img: "/images/paint-peeling-off-rough-concrete-wall-scaled.jpg",
    href: "/how-to-repair-peeling-paint-on-wall/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Painting in Hot Weather",
    date: "September 28, 2023",
    readTime: "4 minutes read",
    img: "/images/house-painting-under-sun-scaled.jpg",
    href: "/painting-in-hot-weather/",
    categories: ["Residential painting"],
  },
  {
    title: "Dangers of Delaying an Exterior Paint Job",
    date: "September 21, 2023",
    readTime: "4 minutes read",
    img: "/images/beautiful-house-exterior.jpg",
    href: "/dangers-of-delaying-exterior-paint-job/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Prepare Surface For Painting",
    date: "September 17, 2023",
    readTime: "6 minutes read",
    img: "/images/surface-prep-for-painting.jpg",
    href: "/how-to-prepare-surface-for-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Guide to Textured Paint: 9 Types of Texture Paint Finishes",
    date: "September 14, 2023",
    readTime: "9 minutes read",
    img: "/images/green-wall-paint-textured-background-scaled.jpg",
    href: "/different-types-of-textured-paint-for-walls/",
    categories: ["Commercial Painting", "Residential painting"],
  },
  {
    title: "How Long Does It Take to Paint a House?",
    date: "September 7, 2023",
    readTime: "3 minutes read",
    img: "/images/couple-painting-interior-wall-new-apartment-scaled.jpg",
    href: "/how-long-to-paint-a-house/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Remove Popcorn Ceilings: Easy Tips and Tricks",
    date: "August 31, 2023",
    readTime: "8 minutes read",
    img: "/images/popcorn-ceiling.jpg",
    href: "/how-to-remove-popcorn-vermiculite-ceilings/",
    categories: ["Residential painting"],
  },
  {
    title: "Plan for Your Next Commercial Painting Project",
    date: "August 28, 2023",
    readTime: "3 minutes read",
    img: "/images/painter-spraying-powder-paint-from-gun.jpg",
    href: "/plan-for-your-next-commercial-painting-project/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How Paint Colour Can Change The Perceived Size Of A Room",
    date: "August 21, 2023",
    readTime: "3 minutes read",
    img: "/images/interior-design-with-photoframes-couch.jpg",
    href: "/how-paint-colour-change-size-of-room/",
    categories: ["Residential painting"],
  },
  {
    title: "Painting Your House Before Selling",
    date: "August 14, 2023",
    readTime: "3 minutes read",
    img: "/images/house-with-yard-sign-sale.jpg",
    href: "/painting-your-house-before-selling/",
    categories: ["Residential painting"],
  },
  {
    title: "How to Choose the Best Strata Painters in Sydney",
    date: "August 7, 2023",
    readTime: "4 minutes read",
    img: "/images/new-buildings-with-green-areas.jpg",
    href: "/how-to-choose-best-strata-painters-sydney/",
    categories: ["Commercial Painting"],
  },
  {
    title: "5 Strategies to Save Money When Hiring Sydney Painters",
    date: "July 24, 2023",
    readTime: "4 minutes read",
    img: "/images/house-painter-sydney.jpg",
    href: "/tips-to-save-money-when-hiring-sydney-painters/",
    categories: ["Residential painting"],
  },
  {
    title: "The Benefits of Hiring Professional Painters in Sydney",
    date: "July 18, 2023",
    readTime: "4 minutes read",
    img: "/images/professional-painters-blog-banner.jpg",
    href: "/benefits-of-hiring-professional-painters-sydney/",
    categories: ["Residential painting"],
  },
  {
    title: "Garage Floor Painting vs Epoxy Coating",
    date: "July 12, 2023",
    readTime: "3 minutes read",
    img: "/images/neon-light-inside-parking-garage.jpg",
    href: "/garage-floor-painting-vs-epoxy-coating/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Find the Best Sydney Painting Services",
    date: "July 6, 2023",
    readTime: "4 minutes read",
    img: "/images/painters-in-sydney.jpg",
    href: "/how-to-find-best-sydney-painting-services/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Most Common Commercial Painting Mistakes to Avoid",
    date: "June 29, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-building-blog-banner-1.jpg",
    href: "/common-commercial-painting-mistakes-to-avoid/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Signs You Need to Hire Residential Painters in Sydney",
    date: "June 22, 2023",
    readTime: "3 minutes read",
    img: "/images/paint-workspace-remodel-design.jpg",
    href: "/signs-you-need-to-hire-residential-painters-sydney/",
    categories: ["Residential painting"],
  },
  {
    title: "Factors to Consider When Choosing Commercial Painters",
    date: "June 15, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-painters-sydney-blog-banner.jpg",
    href: "/factors-when-choosing-commercial-painters/",
    categories: ["Commercial Painting"],
  },
  {
    title: "What to Expect from Sydney Painters",
    date: "June 8, 2023",
    readTime: "3 minutes read",
    img: "/images/decorators-painting-a-wall-with-a-roller-during-renovation-scaled.jpg",
    href: "/what-to-expect-from-sydney-painters/",
    categories: ["Residential painting"],
  },
  {
    title: "Only Hire the Best Commercial Painting Contractors",
    date: "May 25, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-painting-blog-banner.jpg",
    href: "/hire-the-best-commercial-painting-contractors/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How Commercial Painters in Sydney Can Transform Your Property",
    date: "May 18, 2023",
    readTime: "3 minutes read",
    img: "/images/white-commercial-building-sydney.jpg",
    href: "/commercial-painters-sydney-can-transform-your-property/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Tips for Painting Your Ceilings",
    date: "May 15, 2023",
    readTime: "6 minutes read",
    img: "/images/how-to-paint-ceilings-blog-banner.jpg",
    href: "/tips-for-painting-your-ceilings/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Get Your Epoxy Flooring Done with Our Epoxy Floor Coating Experts in Sydney",
    date: "May 11, 2023",
    readTime: "3 minutes read",
    img: "/images/epoxy-floor-coatings-1.jpg",
    href: "/get-your-epoxy-flooring-done-with-priority-one-coatings/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Hiring the Right Epoxy Flooring Contractors in Sydney",
    date: "May 4, 2023",
    readTime: "4 minutes read",
    img: "/images/epoxy-flooring-blog-banner.jpg",
    href: "/hiring-the-right-epoxy-flooring-contractors-in-sydney/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Keep Your Property Looking Fresh with The Leading Painting Services in Sydney",
    date: "April 27, 2023",
    readTime: "3 minutes read",
    img: "/images/transform-the-appearance-of-your-property.jpg",
    href: "/keep-your-property-looking-fresh-with-priority-one-coatings/",
    categories: ["Residential painting"],
  },
  {
    title: "Looking for Commercial Painting Sydney-wide? Hire Priority One Coatings",
    date: "April 20, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-building-painting-sydney.jpg",
    href: "/for-commercial-painting-sydney-hire-priority-one-coatings/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Refresh Your Multi-Level Building With Sydney Painting Services",
    date: "April 13, 2023",
    readTime: "3 minutes read",
    img: "/images/office-skyscrapers-business-district.jpg",
    href: "/refresh-multi-level-building-with-sydney-painting-services/",
    categories: ["News"],
  },
  {
    title: "Only Trust the Best Commercial Painters in Sydney",
    date: "April 6, 2023",
    readTime: "3 minutes read",
    img: "/images/best-commercial-painters-sydney-blog-banner.jpg",
    href: "/trust-the-best-commercial-painters-in-sydney/",
    categories: ["News"],
  },
  {
    title: "How to Hire Sydney Painting Services?",
    date: "March 28, 2023",
    readTime: "3 minutes read",
    img: "/images/sydney-painting-services-blog-banner.jpg",
    href: "/how-to-hire-sydney-painting-services/",
    categories: ["News"],
  },
  {
    title: "Best Epoxy Floor Coatings for Commercial Space",
    date: "March 21, 2023",
    readTime: "3 minutes read",
    img: "/images/epoxy-flooring-for-commercial-space-banner.jpg",
    href: "/best-epoxy-floor-coatings-for-commercial-space/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Common Commercial Paint Problems & Solutions",
    date: "March 16, 2023",
    readTime: "7 minutes read",
    img: "/images/commercial-paint-problems-solution-banner.jpg",
    href: "/common-commercial-paint-problems-solutions/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Our Sydney Strata Painters Can Perform Any Large-Scale Job",
    date: "March 14, 2023",
    readTime: "3 minutes read",
    img: "/images/strata-building-blog-banner.jpg",
    href: "/sydney-strata-painters-perform-large-scale-job/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Priority One Coatings Will Make Your Sydney Office Stand Out",
    date: "March 7, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-fitouts-sydney.jpg",
    href: "/priority-coatings-make-your-sydney-office-stand-out/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Make Sure You Use the Best Epoxy Floor Coatings in Sydney",
    date: "February 28, 2023",
    readTime: "3 minutes read",
    img: "/images/epoxy-floor-coatings-in-sydney-banner.jpg",
    href: "/use-the-best-epoxy-floor-coatings-sydney/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Our Commercial Fitouts Sydney Specialists Can Perform Any Job",
    date: "February 21, 2023",
    readTime: "3 minutes read",
    img: "/images/commercial-office-fitouts.jpg",
    href: "/our-commercial-fitouts-sydney-perform-any-job/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Remove Water Stains on Walls & Ceilings",
    date: "February 16, 2023",
    readTime: "8 minutes read",
    img: "/images/water-stain-on-walls-and-ceilings.png",
    href: "/how-to-remove-water-stains-from-walls-and-ceilings/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "Work with The Best Commercial Painters in Sydney",
    date: "February 14, 2023",
    readTime: "2 minutes read",
    img: "/images/commercial-painters.jpg",
    href: "/work-with-best-commercial-painters-in-sydney/",
    categories: ["News"],
  },
  {
    title: "Need Painters in Sydney? Priority One Coatings Can Help",
    date: "February 7, 2023",
    readTime: "2 minutes read",
    img: "/images/sydney-painters-priority-one-coatings.jpg",
    href: "/need-painters-sydney-priority-one-coatings-can-help/",
    categories: ["News"],
  },
  {
    title: "Benefits of Repainting Your Commercial Building",
    date: "January 31, 2023",
    readTime: "6 minutes read",
    img: "/images/repainting-your-commercial-building.jpg",
    href: "/benefits-of-repainting-commercial-building/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Maintain Your Commercial Painting Project",
    date: "December 22, 2022",
    readTime: "6 minutes read",
    img: "/images/bright-new-commercial-buildings.jpg",
    href: "/how-to-maintain-commercial-painting-project/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Paint a Commercial Building?",
    date: "November 22, 2022",
    readTime: "5 minutes read",
    img: "/images/paint-commercial-building.jpg",
    href: "/how-to-paint-commercial-building/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How To Treat Lead Paint Found in A Commercial Building?",
    date: "October 6, 2022",
    readTime: "6 minutes read",
    img: "/images/lead-based-paint-removal.jpg",
    href: "/how-to-treat-lead-paint-in-commercial-building/",
    categories: ["Commercial Painting"],
  },
  {
    title: "How to Calculate Average Cost of Interior and Exterior House Painting",
    date: "September 26, 2022",
    readTime: "6 minutes read",
    img: "/images/calculate-the-cost-of-house-painting.jpg",
    href: "/calculate-average-cost-of-interior-exterior-painting/",
    categories: ["DIY", "Residential painting"],
  },
  {
    title: "8 Practical Ways to Choose the Right Partitions for Your Office",
    date: "December 19, 2021",
    readTime: "5 minutes read",
    img: "/images/Ways-to-choose-the-suitable-office-partitions.png",
    href: "/practical-ways-to-choose-suitable-office-partitions/",
    categories: ["Commercial Painting"],
  },
  {
    title: "Tips on Choosing a Licensed House Painter in Sydney",
    date: "October 14, 2021",
    readTime: "5 minutes read",
    img: "/images/licensed-house-painter-1.jpg",
    href: "/tips-on-choosing-a-licensed-house-painter-within-sydney/",
    categories: ["Residential painting"],
  },
];

export const FEATURED_POST = POSTS.find((post) => post.href === "/dulux-colour-forecast-for-2026/")!;
export const RECENT_POSTS = POSTS.filter((post) => post !== FEATURED_POST).slice(0, 5);

export const POSTS_PER_PAGE = 10;

export function paginate(posts: BlogPost[], page: number) {
  const totalPages = Math.max(1, Math.ceil(posts.length / POSTS_PER_PAGE));
  const start = (page - 1) * POSTS_PER_PAGE;
  return { items: posts.slice(start, start + POSTS_PER_PAGE), totalPages };
}
